// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chainrep/v1/transport.proto

package grpcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{0}
}

type FailureDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureDomain) Reset() {
	*x = FailureDomain{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureDomain) ProtoMessage() {}

func (x *FailureDomain) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureDomain.ProtoReflect.Descriptor instead.
func (*FailureDomain) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *FailureDomain) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FailureDomain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Node struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RpcAddress     string                 `protobuf:"bytes,2,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
	FailureDomains []*FailureDomain       `protobuf:"bytes,3,rep,name=failure_domains,json=failureDomains,proto3" json:"failure_domains,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetRpcAddress() string {
	if x != nil {
		return x.RpcAddress
	}
	return ""
}

func (x *Node) GetFailureDomains() []*FailureDomain {
	if x != nil {
		return x.FailureDomains
	}
	return nil
}

type BootstrapRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommandId         string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExpectedVersion   uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	SlotCount         int32                  `protobuf:"varint,3,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Nodes             []*Node                `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *BootstrapRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *BootstrapRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *BootstrapRequest) GetSlotCount() int32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *BootstrapRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *BootstrapRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MembershipMutationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandId        string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ExpectedVersion  uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	MaxChangedChains int32                  `protobuf:"varint,3,opt,name=max_changed_chains,json=maxChangedChains,proto3" json:"max_changed_chains,omitempty"`
	Node             *Node                  `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	NodeId           string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MembershipMutationRequest) Reset() {
	*x = MembershipMutationRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipMutationRequest) ProtoMessage() {}

func (x *MembershipMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipMutationRequest.ProtoReflect.Descriptor instead.
func (*MembershipMutationRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *MembershipMutationRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MembershipMutationRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *MembershipMutationRequest) GetMaxChangedChains() int32 {
	if x != nil {
		return x.MaxChangedChains
	}
	return 0
}

func (x *MembershipMutationRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *MembershipMutationRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ServerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *ServerState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RoutingSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingSnapshotRequest) Reset() {
	*x = RoutingSnapshotRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSnapshotRequest) ProtoMessage() {}

func (x *RoutingSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RoutingSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{6}
}

type SlotRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ChainVersion  uint64                 `protobuf:"varint,2,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	HeadNodeId    string                 `protobuf:"bytes,3,opt,name=head_node_id,json=headNodeId,proto3" json:"head_node_id,omitempty"`
	HeadEndpoint  string                 `protobuf:"bytes,4,opt,name=head_endpoint,json=headEndpoint,proto3" json:"head_endpoint,omitempty"`
	TailNodeId    string                 `protobuf:"bytes,5,opt,name=tail_node_id,json=tailNodeId,proto3" json:"tail_node_id,omitempty"`
	TailEndpoint  string                 `protobuf:"bytes,6,opt,name=tail_endpoint,json=tailEndpoint,proto3" json:"tail_endpoint,omitempty"`
	Writable      bool                   `protobuf:"varint,7,opt,name=writable,proto3" json:"writable,omitempty"`
	Readable      bool                   `protobuf:"varint,8,opt,name=readable,proto3" json:"readable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotRoute) Reset() {
	*x = SlotRoute{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRoute) ProtoMessage() {}

func (x *SlotRoute) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRoute.ProtoReflect.Descriptor instead.
func (*SlotRoute) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{7}
}

func (x *SlotRoute) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotRoute) GetChainVersion() uint64 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *SlotRoute) GetHeadNodeId() string {
	if x != nil {
		return x.HeadNodeId
	}
	return ""
}

func (x *SlotRoute) GetHeadEndpoint() string {
	if x != nil {
		return x.HeadEndpoint
	}
	return ""
}

func (x *SlotRoute) GetTailNodeId() string {
	if x != nil {
		return x.TailNodeId
	}
	return ""
}

func (x *SlotRoute) GetTailEndpoint() string {
	if x != nil {
		return x.TailEndpoint
	}
	return ""
}

func (x *SlotRoute) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *SlotRoute) GetReadable() bool {
	if x != nil {
		return x.Readable
	}
	return false
}

type RoutingSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SlotCount     int32                  `protobuf:"varint,2,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	Slots         []*SlotRoute           `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingSnapshotResponse) Reset() {
	*x = RoutingSnapshotResponse{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingSnapshotResponse) ProtoMessage() {}

func (x *RoutingSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RoutingSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{8}
}

func (x *RoutingSnapshotResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RoutingSnapshotResponse) GetSlotCount() int32 {
	if x != nil {
		return x.SlotCount
	}
	return 0
}

func (x *RoutingSnapshotResponse) GetSlots() []*SlotRoute {
	if x != nil {
		return x.Slots
	}
	return nil
}

type ReplicaReadyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaReadyReport) Reset() {
	*x = ReplicaReadyReport{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaReadyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaReadyReport) ProtoMessage() {}

func (x *ReplicaReadyReport) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaReadyReport.ProtoReflect.Descriptor instead.
func (*ReplicaReadyReport) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicaReadyReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaReadyReport) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReplicaReadyReport) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ReplicaRemovedReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaRemovedReport) Reset() {
	*x = ReplicaRemovedReport{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaRemovedReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaRemovedReport) ProtoMessage() {}

func (x *ReplicaRemovedReport) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaRemovedReport.ProtoReflect.Descriptor instead.
func (*ReplicaRemovedReport) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicaRemovedReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReplicaRemovedReport) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReplicaRemovedReport) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReplicaCount    int32                  `protobuf:"varint,2,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	ActiveCount     int32                  `protobuf:"varint,3,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	CatchingUpCount int32                  `protobuf:"varint,4,opt,name=catching_up_count,json=catchingUpCount,proto3" json:"catching_up_count,omitempty"`
	LeavingCount    int32                  `protobuf:"varint,5,opt,name=leaving_count,json=leavingCount,proto3" json:"leaving_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{11}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetReplicaCount() int32 {
	if x != nil {
		return x.ReplicaCount
	}
	return 0
}

func (x *NodeStatus) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *NodeStatus) GetCatchingUpCount() int32 {
	if x != nil {
		return x.CatchingUpCount
	}
	return 0
}

func (x *NodeStatus) GetLeavingCount() int32 {
	if x != nil {
		return x.LeavingCount
	}
	return 0
}

type ChainPeers struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PredecessorNodeId string                 `protobuf:"bytes,1,opt,name=predecessor_node_id,json=predecessorNodeId,proto3" json:"predecessor_node_id,omitempty"`
	PredecessorTarget string                 `protobuf:"bytes,2,opt,name=predecessor_target,json=predecessorTarget,proto3" json:"predecessor_target,omitempty"`
	SuccessorNodeId   string                 `protobuf:"bytes,3,opt,name=successor_node_id,json=successorNodeId,proto3" json:"successor_node_id,omitempty"`
	SuccessorTarget   string                 `protobuf:"bytes,4,opt,name=successor_target,json=successorTarget,proto3" json:"successor_target,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChainPeers) Reset() {
	*x = ChainPeers{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainPeers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainPeers) ProtoMessage() {}

func (x *ChainPeers) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainPeers.ProtoReflect.Descriptor instead.
func (*ChainPeers) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{12}
}

func (x *ChainPeers) GetPredecessorNodeId() string {
	if x != nil {
		return x.PredecessorNodeId
	}
	return ""
}

func (x *ChainPeers) GetPredecessorTarget() string {
	if x != nil {
		return x.PredecessorTarget
	}
	return ""
}

func (x *ChainPeers) GetSuccessorNodeId() string {
	if x != nil {
		return x.SuccessorNodeId
	}
	return ""
}

func (x *ChainPeers) GetSuccessorTarget() string {
	if x != nil {
		return x.SuccessorTarget
	}
	return ""
}

type ReplicaAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ChainVersion  uint64                 `protobuf:"varint,2,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Peers         *ChainPeers            `protobuf:"bytes,4,opt,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaAssignment) Reset() {
	*x = ReplicaAssignment{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaAssignment) ProtoMessage() {}

func (x *ReplicaAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaAssignment.ProtoReflect.Descriptor instead.
func (*ReplicaAssignment) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{13}
}

func (x *ReplicaAssignment) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReplicaAssignment) GetChainVersion() uint64 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *ReplicaAssignment) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ReplicaAssignment) GetPeers() *ChainPeers {
	if x != nil {
		return x.Peers
	}
	return nil
}

type RecoveredReplica struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Assignment               *ReplicaAssignment     `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	LastKnownState           string                 `protobuf:"bytes,2,opt,name=last_known_state,json=lastKnownState,proto3" json:"last_known_state,omitempty"`
	HighestCommittedSequence uint64                 `protobuf:"varint,3,opt,name=highest_committed_sequence,json=highestCommittedSequence,proto3" json:"highest_committed_sequence,omitempty"`
	HasCommittedData         bool                   `protobuf:"varint,4,opt,name=has_committed_data,json=hasCommittedData,proto3" json:"has_committed_data,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RecoveredReplica) Reset() {
	*x = RecoveredReplica{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveredReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveredReplica) ProtoMessage() {}

func (x *RecoveredReplica) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveredReplica.ProtoReflect.Descriptor instead.
func (*RecoveredReplica) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{14}
}

func (x *RecoveredReplica) GetAssignment() *ReplicaAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *RecoveredReplica) GetLastKnownState() string {
	if x != nil {
		return x.LastKnownState
	}
	return ""
}

func (x *RecoveredReplica) GetHighestCommittedSequence() uint64 {
	if x != nil {
		return x.HighestCommittedSequence
	}
	return 0
}

func (x *RecoveredReplica) GetHasCommittedData() bool {
	if x != nil {
		return x.HasCommittedData
	}
	return false
}

type NodeRecoveryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Replicas      []*RecoveredReplica    `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRecoveryReport) Reset() {
	*x = NodeRecoveryReport{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRecoveryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRecoveryReport) ProtoMessage() {}

func (x *NodeRecoveryReport) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRecoveryReport.ProtoReflect.Descriptor instead.
func (*NodeRecoveryReport) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{15}
}

func (x *NodeRecoveryReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeRecoveryReport) GetReplicas() []*RecoveredReplica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type AddReplicaAsTailCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *ReplicaAssignment     `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicaAsTailCommand) Reset() {
	*x = AddReplicaAsTailCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicaAsTailCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicaAsTailCommand) ProtoMessage() {}

func (x *AddReplicaAsTailCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicaAsTailCommand.ProtoReflect.Descriptor instead.
func (*AddReplicaAsTailCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{16}
}

func (x *AddReplicaAsTailCommand) GetAssignment() *ReplicaAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type ActivateReplicaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateReplicaCommand) Reset() {
	*x = ActivateReplicaCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateReplicaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateReplicaCommand) ProtoMessage() {}

func (x *ActivateReplicaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateReplicaCommand.ProtoReflect.Descriptor instead.
func (*ActivateReplicaCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateReplicaCommand) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type MarkReplicaLeavingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReplicaLeavingCommand) Reset() {
	*x = MarkReplicaLeavingCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReplicaLeavingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReplicaLeavingCommand) ProtoMessage() {}

func (x *MarkReplicaLeavingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReplicaLeavingCommand.ProtoReflect.Descriptor instead.
func (*MarkReplicaLeavingCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{18}
}

func (x *MarkReplicaLeavingCommand) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type RemoveReplicaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicaCommand) Reset() {
	*x = RemoveReplicaCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicaCommand) ProtoMessage() {}

func (x *RemoveReplicaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicaCommand.ProtoReflect.Descriptor instead.
func (*RemoveReplicaCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveReplicaCommand) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type UpdateChainPeersCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *ReplicaAssignment     `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChainPeersCommand) Reset() {
	*x = UpdateChainPeersCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChainPeersCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChainPeersCommand) ProtoMessage() {}

func (x *UpdateChainPeersCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChainPeersCommand.ProtoReflect.Descriptor instead.
func (*UpdateChainPeersCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateChainPeersCommand) GetAssignment() *ReplicaAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type ResumeRecoveredReplicaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *ReplicaAssignment     `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRecoveredReplicaCommand) Reset() {
	*x = ResumeRecoveredReplicaCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRecoveredReplicaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRecoveredReplicaCommand) ProtoMessage() {}

func (x *ResumeRecoveredReplicaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRecoveredReplicaCommand.ProtoReflect.Descriptor instead.
func (*ResumeRecoveredReplicaCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{21}
}

func (x *ResumeRecoveredReplicaCommand) GetAssignment() *ReplicaAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type RecoverReplicaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *ReplicaAssignment     `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverReplicaCommand) Reset() {
	*x = RecoverReplicaCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverReplicaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverReplicaCommand) ProtoMessage() {}

func (x *RecoverReplicaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverReplicaCommand.ProtoReflect.Descriptor instead.
func (*RecoverReplicaCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{22}
}

func (x *RecoverReplicaCommand) GetAssignment() *ReplicaAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *RecoverReplicaCommand) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

type DropRecoveredReplicaCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropRecoveredReplicaCommand) Reset() {
	*x = DropRecoveredReplicaCommand{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropRecoveredReplicaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropRecoveredReplicaCommand) ProtoMessage() {}

func (x *DropRecoveredReplicaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropRecoveredReplicaCommand.ProtoReflect.Descriptor instead.
func (*DropRecoveredReplicaCommand) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{23}
}

func (x *DropRecoveredReplicaCommand) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type ClientGetRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Key                  string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedChainVersion uint64                 `protobuf:"varint,3,opt,name=expected_chain_version,json=expectedChainVersion,proto3" json:"expected_chain_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientGetRequest) Reset() {
	*x = ClientGetRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetRequest) ProtoMessage() {}

func (x *ClientGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetRequest.ProtoReflect.Descriptor instead.
func (*ClientGetRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{24}
}

func (x *ClientGetRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ClientGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientGetRequest) GetExpectedChainVersion() uint64 {
	if x != nil {
		return x.ExpectedChainVersion
	}
	return 0
}

type ClientPutRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Key                  string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedChainVersion uint64                 `protobuf:"varint,4,opt,name=expected_chain_version,json=expectedChainVersion,proto3" json:"expected_chain_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientPutRequest) Reset() {
	*x = ClientPutRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPutRequest) ProtoMessage() {}

func (x *ClientPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPutRequest.ProtoReflect.Descriptor instead.
func (*ClientPutRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{25}
}

func (x *ClientPutRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ClientPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientPutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClientPutRequest) GetExpectedChainVersion() uint64 {
	if x != nil {
		return x.ExpectedChainVersion
	}
	return 0
}

type ClientDeleteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Key                  string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedChainVersion uint64                 `protobuf:"varint,3,opt,name=expected_chain_version,json=expectedChainVersion,proto3" json:"expected_chain_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClientDeleteRequest) Reset() {
	*x = ClientDeleteRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDeleteRequest) ProtoMessage() {}

func (x *ClientDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDeleteRequest.ProtoReflect.Descriptor instead.
func (*ClientDeleteRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{26}
}

func (x *ClientDeleteRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ClientDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientDeleteRequest) GetExpectedChainVersion() uint64 {
	if x != nil {
		return x.ExpectedChainVersion
	}
	return 0
}

type CommitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResult) Reset() {
	*x = CommitResult{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResult) ProtoMessage() {}

func (x *CommitResult) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResult.ProtoReflect.Descriptor instead.
func (*CommitResult) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{27}
}

func (x *CommitResult) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitResult) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReadResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ChainVersion  uint64                 `protobuf:"varint,2,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{28}
}

func (x *ReadResult) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ReadResult) GetChainVersion() uint64 {
	if x != nil {
		return x.ChainVersion
	}
	return 0
}

func (x *ReadResult) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReadResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WriteOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperation) Reset() {
	*x = WriteOperation{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperation) ProtoMessage() {}

func (x *WriteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperation.ProtoReflect.Descriptor instead.
func (*WriteOperation) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{29}
}

func (x *WriteOperation) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *WriteOperation) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *WriteOperation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WriteOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteOperation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ForwardWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *WriteOperation        `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWriteRequest) Reset() {
	*x = ForwardWriteRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWriteRequest) ProtoMessage() {}

func (x *ForwardWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWriteRequest.ProtoReflect.Descriptor instead.
func (*ForwardWriteRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{30}
}

func (x *ForwardWriteRequest) GetOperation() *WriteOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ForwardWriteRequest) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

type CommitWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,3,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitWriteRequest) Reset() {
	*x = CommitWriteRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitWriteRequest) ProtoMessage() {}

func (x *CommitWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitWriteRequest.ProtoReflect.Descriptor instead.
func (*CommitWriteRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{31}
}

func (x *CommitWriteRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CommitWriteRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommitWriteRequest) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

type FetchSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchSnapshotRequest) Reset() {
	*x = FetchSnapshotRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnapshotRequest) ProtoMessage() {}

func (x *FetchSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnapshotRequest.ProtoReflect.Descriptor instead.
func (*FetchSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{32}
}

func (x *FetchSnapshotRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type SnapshotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEntry) Reset() {
	*x = SnapshotEntry{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntry) ProtoMessage() {}

func (x *SnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntry.ProtoReflect.Descriptor instead.
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{33}
}

func (x *SnapshotEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FetchCommittedSequenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommittedSequenceRequest) Reset() {
	*x = FetchCommittedSequenceRequest{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommittedSequenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommittedSequenceRequest) ProtoMessage() {}

func (x *FetchCommittedSequenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommittedSequenceRequest.ProtoReflect.Descriptor instead.
func (*FetchCommittedSequenceRequest) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{34}
}

func (x *FetchCommittedSequenceRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type FetchCommittedSequenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchCommittedSequenceResponse) Reset() {
	*x = FetchCommittedSequenceResponse{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchCommittedSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCommittedSequenceResponse) ProtoMessage() {}

func (x *FetchCommittedSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCommittedSequenceResponse.ProtoReflect.Descriptor instead.
func (*FetchCommittedSequenceResponse) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{35}
}

func (x *FetchCommittedSequenceResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RoutingMismatchDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ExpectedChainVersion uint64                 `protobuf:"varint,2,opt,name=expected_chain_version,json=expectedChainVersion,proto3" json:"expected_chain_version,omitempty"`
	CurrentChainVersion  uint64                 `protobuf:"varint,3,opt,name=current_chain_version,json=currentChainVersion,proto3" json:"current_chain_version,omitempty"`
	CurrentRole          string                 `protobuf:"bytes,4,opt,name=current_role,json=currentRole,proto3" json:"current_role,omitempty"`
	CurrentState         string                 `protobuf:"bytes,5,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Reason               string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RoutingMismatchDetail) Reset() {
	*x = RoutingMismatchDetail{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingMismatchDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingMismatchDetail) ProtoMessage() {}

func (x *RoutingMismatchDetail) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingMismatchDetail.ProtoReflect.Descriptor instead.
func (*RoutingMismatchDetail) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{36}
}

func (x *RoutingMismatchDetail) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RoutingMismatchDetail) GetExpectedChainVersion() uint64 {
	if x != nil {
		return x.ExpectedChainVersion
	}
	return 0
}

func (x *RoutingMismatchDetail) GetCurrentChainVersion() uint64 {
	if x != nil {
		return x.CurrentChainVersion
	}
	return 0
}

func (x *RoutingMismatchDetail) GetCurrentRole() string {
	if x != nil {
		return x.CurrentRole
	}
	return ""
}

func (x *RoutingMismatchDetail) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *RoutingMismatchDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AmbiguousWriteDetail struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Slot                 int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Kind                 string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ExpectedChainVersion uint64                 `protobuf:"varint,3,opt,name=expected_chain_version,json=expectedChainVersion,proto3" json:"expected_chain_version,omitempty"`
	Cause                string                 `protobuf:"bytes,4,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AmbiguousWriteDetail) Reset() {
	*x = AmbiguousWriteDetail{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmbiguousWriteDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmbiguousWriteDetail) ProtoMessage() {}

func (x *AmbiguousWriteDetail) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmbiguousWriteDetail.ProtoReflect.Descriptor instead.
func (*AmbiguousWriteDetail) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{37}
}

func (x *AmbiguousWriteDetail) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AmbiguousWriteDetail) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AmbiguousWriteDetail) GetExpectedChainVersion() uint64 {
	if x != nil {
		return x.ExpectedChainVersion
	}
	return 0
}

func (x *AmbiguousWriteDetail) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type BackpressureDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Current       int32                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Cause         string                 `protobuf:"bytes,5,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackpressureDetail) Reset() {
	*x = BackpressureDetail{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpressureDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpressureDetail) ProtoMessage() {}

func (x *BackpressureDetail) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpressureDetail.ProtoReflect.Descriptor instead.
func (*BackpressureDetail) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{38}
}

func (x *BackpressureDetail) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *BackpressureDetail) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *BackpressureDetail) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BackpressureDetail) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *BackpressureDetail) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type DomainErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainErrorDetail) Reset() {
	*x = DomainErrorDetail{}
	mi := &file_chainrep_v1_transport_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainErrorDetail) ProtoMessage() {}

func (x *DomainErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_chainrep_v1_transport_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainErrorDetail.ProtoReflect.Descriptor instead.
func (*DomainErrorDetail) Descriptor() ([]byte, []int) {
	return file_chainrep_v1_transport_proto_rawDescGZIP(), []int{39}
}

func (x *DomainErrorDetail) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DomainErrorDetail) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DomainErrorDetail) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DomainErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_chainrep_v1_transport_proto protoreflect.FileDescriptor

const file_chainrep_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1bchainrep/v1/transport.proto\x12\vchainrep.v1\"\a\n" +
	"\x05Empty\"7\n" +
	"\rFailureDomain\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"|\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vrpc_address\x18\x02 \x01(\tR\n" +
	"rpcAddress\x12C\n" +
	"\x0ffailure_domains\x18\x03 \x03(\v2\x1a.chainrep.v1.FailureDomainR\x0efailureDomains\"\xd3\x01\n" +
	"\x10BootstrapRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\x12\x1d\n" +
	"\n" +
	"slot_count\x18\x03 \x01(\x05R\tslotCount\x12-\n" +
	"\x12replication_factor\x18\x04 \x01(\x05R\x11replicationFactor\x12'\n" +
	"\x05nodes\x18\x05 \x03(\v2\x11.chainrep.v1.NodeR\x05nodes\"\xd3\x01\n" +
	"\x19MembershipMutationRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\x12,\n" +
	"\x12max_changed_chains\x18\x03 \x01(\x05R\x10maxChangedChains\x12%\n" +
	"\x04node\x18\x04 \x01(\v2\x11.chainrep.v1.NodeR\x04node\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\"'\n" +
	"\vServerState\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x18\n" +
	"\x16RoutingSnapshotRequest\"\x8a\x02\n" +
	"\tSlotRoute\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12#\n" +
	"\rchain_version\x18\x02 \x01(\x04R\fchainVersion\x12 \n" +
	"\fhead_node_id\x18\x03 \x01(\tR\n" +
	"headNodeId\x12#\n" +
	"\rhead_endpoint\x18\x04 \x01(\tR\fheadEndpoint\x12 \n" +
	"\ftail_node_id\x18\x05 \x01(\tR\n" +
	"tailNodeId\x12#\n" +
	"\rtail_endpoint\x18\x06 \x01(\tR\ftailEndpoint\x12\x1a\n" +
	"\bwritable\x18\a \x01(\bR\bwritable\x12\x1a\n" +
	"\breadable\x18\b \x01(\bR\breadable\"\x80\x01\n" +
	"\x17RoutingSnapshotResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"slot_count\x18\x02 \x01(\x05R\tslotCount\x12,\n" +
	"\x05slots\x18\x03 \x03(\v2\x16.chainrep.v1.SlotRouteR\x05slots\"`\n" +
	"\x12ReplicaReadyReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"b\n" +
	"\x14ReplicaRemovedReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"\xbe\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rreplica_count\x18\x02 \x01(\x05R\freplicaCount\x12!\n" +
	"\factive_count\x18\x03 \x01(\x05R\vactiveCount\x12*\n" +
	"\x11catching_up_count\x18\x04 \x01(\x05R\x0fcatchingUpCount\x12#\n" +
	"\rleaving_count\x18\x05 \x01(\x05R\fleavingCount\"\xc2\x01\n" +
	"\n" +
	"ChainPeers\x12.\n" +
	"\x13predecessor_node_id\x18\x01 \x01(\tR\x11predecessorNodeId\x12-\n" +
	"\x12predecessor_target\x18\x02 \x01(\tR\x11predecessorTarget\x12*\n" +
	"\x11successor_node_id\x18\x03 \x01(\tR\x0fsuccessorNodeId\x12)\n" +
	"\x10successor_target\x18\x04 \x01(\tR\x0fsuccessorTarget\"\x8f\x01\n" +
	"\x11ReplicaAssignment\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12#\n" +
	"\rchain_version\x18\x02 \x01(\x04R\fchainVersion\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12-\n" +
	"\x05peers\x18\x04 \x01(\v2\x17.chainrep.v1.ChainPeersR\x05peers\"\xe8\x01\n" +
	"\x10RecoveredReplica\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.chainrep.v1.ReplicaAssignmentR\n" +
	"assignment\x12(\n" +
	"\x10last_known_state\x18\x02 \x01(\tR\x0elastKnownState\x12<\n" +
	"\x1ahighest_committed_sequence\x18\x03 \x01(\x04R\x18highestCommittedSequence\x12,\n" +
	"\x12has_committed_data\x18\x04 \x01(\bR\x10hasCommittedData\"h\n" +
	"\x12NodeRecoveryReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\breplicas\x18\x02 \x03(\v2\x1d.chainrep.v1.RecoveredReplicaR\breplicas\"Y\n" +
	"\x17AddReplicaAsTailCommand\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.chainrep.v1.ReplicaAssignmentR\n" +
	"assignment\",\n" +
	"\x16ActivateReplicaCommand\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"/\n" +
	"\x19MarkReplicaLeavingCommand\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"*\n" +
	"\x14RemoveReplicaCommand\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"Y\n" +
	"\x17UpdateChainPeersCommand\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.chainrep.v1.ReplicaAssignmentR\n" +
	"assignment\"_\n" +
	"\x1dResumeRecoveredReplicaCommand\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.chainrep.v1.ReplicaAssignmentR\n" +
	"assignment\"}\n" +
	"\x15RecoverReplicaCommand\x12>\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1e.chainrep.v1.ReplicaAssignmentR\n" +
	"assignment\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\"1\n" +
	"\x1bDropRecoveredReplicaCommand\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"n\n" +
	"\x10ClientGetRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x124\n" +
	"\x16expected_chain_version\x18\x03 \x01(\x04R\x14expectedChainVersion\"\x84\x01\n" +
	"\x10ClientPutRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x124\n" +
	"\x16expected_chain_version\x18\x04 \x01(\x04R\x14expectedChainVersion\"q\n" +
	"\x13ClientDeleteRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x124\n" +
	"\x16expected_chain_version\x18\x03 \x01(\x04R\x14expectedChainVersion\">\n" +
	"\fCommitResult\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"q\n" +
	"\n" +
	"ReadResult\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12#\n" +
	"\rchain_version\x18\x02 \x01(\x04R\fchainVersion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"|\n" +
	"\x0eWriteOperation\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"r\n" +
	"\x13ForwardWriteRequest\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.chainrep.v1.WriteOperationR\toperation\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\"f\n" +
	"\x12CommitWriteRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12 \n" +
	"\ffrom_node_id\x18\x03 \x01(\tR\n" +
	"fromNodeId\"*\n" +
	"\x14FetchSnapshotRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"7\n" +
	"\rSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\x1dFetchCommittedSequenceRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\"<\n" +
	"\x1eFetchCommittedSequenceResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\xf5\x01\n" +
	"\x15RoutingMismatchDetail\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x124\n" +
	"\x16expected_chain_version\x18\x02 \x01(\x04R\x14expectedChainVersion\x122\n" +
	"\x15current_chain_version\x18\x03 \x01(\x04R\x13currentChainVersion\x12!\n" +
	"\fcurrent_role\x18\x04 \x01(\tR\vcurrentRole\x12#\n" +
	"\rcurrent_state\x18\x05 \x01(\tR\fcurrentState\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x14AmbiguousWriteDetail\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x124\n" +
	"\x16expected_chain_version\x18\x03 \x01(\x04R\x14expectedChainVersion\x12\x14\n" +
	"\x05cause\x18\x04 \x01(\tR\x05cause\"\x8a\x01\n" +
	"\x12BackpressureDetail\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x14\n" +
	"\x05cause\x18\x05 \x01(\tR\x05cause\"o\n" +
	"\x11DomainErrorDetail\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\xa3\x06\n" +
	"\x12CoordinatorService\x12D\n" +
	"\tBootstrap\x12\x1d.chainrep.v1.BootstrapRequest\x1a\x18.chainrep.v1.ServerState\x12K\n" +
	"\aAddNode\x12&.chainrep.v1.MembershipMutationRequest\x1a\x18.chainrep.v1.ServerState\x12R\n" +
	"\x0eBeginDrainNode\x12&.chainrep.v1.MembershipMutationRequest\x1a\x18.chainrep.v1.ServerState\x12P\n" +
	"\fMarkNodeDead\x12&.chainrep.v1.MembershipMutationRequest\x1a\x18.chainrep.v1.ServerState\x12\\\n" +
	"\x0fRoutingSnapshot\x12#.chainrep.v1.RoutingSnapshotRequest\x1a$.chainrep.v1.RoutingSnapshotResponse\x12O\n" +
	"\x12ReportReplicaReady\x12\x1f.chainrep.v1.ReplicaReadyReport\x1a\x18.chainrep.v1.ServerState\x12S\n" +
	"\x14ReportReplicaRemoved\x12!.chainrep.v1.ReplicaRemovedReport\x1a\x18.chainrep.v1.ServerState\x12B\n" +
	"\x13ReportNodeHeartbeat\x12\x17.chainrep.v1.NodeStatus\x1a\x12.chainrep.v1.Empty\x12J\n" +
	"\x13ReportNodeRecovered\x12\x1f.chainrep.v1.NodeRecoveryReport\x1a\x12.chainrep.v1.Empty\x12@\n" +
	"\x10EvaluateLiveness\x12\x12.chainrep.v1.Empty\x1a\x18.chainrep.v1.ServerState2\xa2\t\n" +
	"\x0eStorageService\x12=\n" +
	"\x03Get\x12\x1d.chainrep.v1.ClientGetRequest\x1a\x17.chainrep.v1.ReadResult\x12?\n" +
	"\x03Put\x12\x1d.chainrep.v1.ClientPutRequest\x1a\x19.chainrep.v1.CommitResult\x12E\n" +
	"\x06Delete\x12 .chainrep.v1.ClientDeleteRequest\x1a\x19.chainrep.v1.CommitResult\x12L\n" +
	"\x10AddReplicaAsTail\x12$.chainrep.v1.AddReplicaAsTailCommand\x1a\x12.chainrep.v1.Empty\x12J\n" +
	"\x0fActivateReplica\x12#.chainrep.v1.ActivateReplicaCommand\x1a\x12.chainrep.v1.Empty\x12P\n" +
	"\x12MarkReplicaLeaving\x12&.chainrep.v1.MarkReplicaLeavingCommand\x1a\x12.chainrep.v1.Empty\x12F\n" +
	"\rRemoveReplica\x12!.chainrep.v1.RemoveReplicaCommand\x1a\x12.chainrep.v1.Empty\x12L\n" +
	"\x10UpdateChainPeers\x12$.chainrep.v1.UpdateChainPeersCommand\x1a\x12.chainrep.v1.Empty\x12X\n" +
	"\x16ResumeRecoveredReplica\x12*.chainrep.v1.ResumeRecoveredReplicaCommand\x1a\x12.chainrep.v1.Empty\x12H\n" +
	"\x0eRecoverReplica\x12\".chainrep.v1.RecoverReplicaCommand\x1a\x12.chainrep.v1.Empty\x12T\n" +
	"\x14DropRecoveredReplica\x12(.chainrep.v1.DropRecoveredReplicaCommand\x1a\x12.chainrep.v1.Empty\x12D\n" +
	"\fForwardWrite\x12 .chainrep.v1.ForwardWriteRequest\x1a\x12.chainrep.v1.Empty\x12B\n" +
	"\vCommitWrite\x12\x1f.chainrep.v1.CommitWriteRequest\x1a\x12.chainrep.v1.Empty\x12P\n" +
	"\rFetchSnapshot\x12!.chainrep.v1.FetchSnapshotRequest\x1a\x1a.chainrep.v1.SnapshotEntry0\x01\x12q\n" +
	"\x16FetchCommittedSequence\x12*.chainrep.v1.FetchCommittedSequenceRequest\x1a+.chainrep.v1.FetchCommittedSequenceResponseBBZ@github.com/danthegoodman1/chainrep/transport/grpcproto;grpcprotob\x06proto3"

var (
	file_chainrep_v1_transport_proto_rawDescOnce sync.Once
	file_chainrep_v1_transport_proto_rawDescData []byte
)

func file_chainrep_v1_transport_proto_rawDescGZIP() []byte {
	file_chainrep_v1_transport_proto_rawDescOnce.Do(func() {
		file_chainrep_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chainrep_v1_transport_proto_rawDesc), len(file_chainrep_v1_transport_proto_rawDesc)))
	})
	return file_chainrep_v1_transport_proto_rawDescData
}

var file_chainrep_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_chainrep_v1_transport_proto_goTypes = []any{
	(*Empty)(nil),                          // 0: chainrep.v1.Empty
	(*FailureDomain)(nil),                  // 1: chainrep.v1.FailureDomain
	(*Node)(nil),                           // 2: chainrep.v1.Node
	(*BootstrapRequest)(nil),               // 3: chainrep.v1.BootstrapRequest
	(*MembershipMutationRequest)(nil),      // 4: chainrep.v1.MembershipMutationRequest
	(*ServerState)(nil),                    // 5: chainrep.v1.ServerState
	(*RoutingSnapshotRequest)(nil),         // 6: chainrep.v1.RoutingSnapshotRequest
	(*SlotRoute)(nil),                      // 7: chainrep.v1.SlotRoute
	(*RoutingSnapshotResponse)(nil),        // 8: chainrep.v1.RoutingSnapshotResponse
	(*ReplicaReadyReport)(nil),             // 9: chainrep.v1.ReplicaReadyReport
	(*ReplicaRemovedReport)(nil),           // 10: chainrep.v1.ReplicaRemovedReport
	(*NodeStatus)(nil),                     // 11: chainrep.v1.NodeStatus
	(*ChainPeers)(nil),                     // 12: chainrep.v1.ChainPeers
	(*ReplicaAssignment)(nil),              // 13: chainrep.v1.ReplicaAssignment
	(*RecoveredReplica)(nil),               // 14: chainrep.v1.RecoveredReplica
	(*NodeRecoveryReport)(nil),             // 15: chainrep.v1.NodeRecoveryReport
	(*AddReplicaAsTailCommand)(nil),        // 16: chainrep.v1.AddReplicaAsTailCommand
	(*ActivateReplicaCommand)(nil),         // 17: chainrep.v1.ActivateReplicaCommand
	(*MarkReplicaLeavingCommand)(nil),      // 18: chainrep.v1.MarkReplicaLeavingCommand
	(*RemoveReplicaCommand)(nil),           // 19: chainrep.v1.RemoveReplicaCommand
	(*UpdateChainPeersCommand)(nil),        // 20: chainrep.v1.UpdateChainPeersCommand
	(*ResumeRecoveredReplicaCommand)(nil),  // 21: chainrep.v1.ResumeRecoveredReplicaCommand
	(*RecoverReplicaCommand)(nil),          // 22: chainrep.v1.RecoverReplicaCommand
	(*DropRecoveredReplicaCommand)(nil),    // 23: chainrep.v1.DropRecoveredReplicaCommand
	(*ClientGetRequest)(nil),               // 24: chainrep.v1.ClientGetRequest
	(*ClientPutRequest)(nil),               // 25: chainrep.v1.ClientPutRequest
	(*ClientDeleteRequest)(nil),            // 26: chainrep.v1.ClientDeleteRequest
	(*CommitResult)(nil),                   // 27: chainrep.v1.CommitResult
	(*ReadResult)(nil),                     // 28: chainrep.v1.ReadResult
	(*WriteOperation)(nil),                 // 29: chainrep.v1.WriteOperation
	(*ForwardWriteRequest)(nil),            // 30: chainrep.v1.ForwardWriteRequest
	(*CommitWriteRequest)(nil),             // 31: chainrep.v1.CommitWriteRequest
	(*FetchSnapshotRequest)(nil),           // 32: chainrep.v1.FetchSnapshotRequest
	(*SnapshotEntry)(nil),                  // 33: chainrep.v1.SnapshotEntry
	(*FetchCommittedSequenceRequest)(nil),  // 34: chainrep.v1.FetchCommittedSequenceRequest
	(*FetchCommittedSequenceResponse)(nil), // 35: chainrep.v1.FetchCommittedSequenceResponse
	(*RoutingMismatchDetail)(nil),          // 36: chainrep.v1.RoutingMismatchDetail
	(*AmbiguousWriteDetail)(nil),           // 37: chainrep.v1.AmbiguousWriteDetail
	(*BackpressureDetail)(nil),             // 38: chainrep.v1.BackpressureDetail
	(*DomainErrorDetail)(nil),              // 39: chainrep.v1.DomainErrorDetail
}
var file_chainrep_v1_transport_proto_depIdxs = []int32{
	1,  // 0: chainrep.v1.Node.failure_domains:type_name -> chainrep.v1.FailureDomain
	2,  // 1: chainrep.v1.BootstrapRequest.nodes:type_name -> chainrep.v1.Node
	2,  // 2: chainrep.v1.MembershipMutationRequest.node:type_name -> chainrep.v1.Node
	7,  // 3: chainrep.v1.RoutingSnapshotResponse.slots:type_name -> chainrep.v1.SlotRoute
	12, // 4: chainrep.v1.ReplicaAssignment.peers:type_name -> chainrep.v1.ChainPeers
	13, // 5: chainrep.v1.RecoveredReplica.assignment:type_name -> chainrep.v1.ReplicaAssignment
	14, // 6: chainrep.v1.NodeRecoveryReport.replicas:type_name -> chainrep.v1.RecoveredReplica
	13, // 7: chainrep.v1.AddReplicaAsTailCommand.assignment:type_name -> chainrep.v1.ReplicaAssignment
	13, // 8: chainrep.v1.UpdateChainPeersCommand.assignment:type_name -> chainrep.v1.ReplicaAssignment
	13, // 9: chainrep.v1.ResumeRecoveredReplicaCommand.assignment:type_name -> chainrep.v1.ReplicaAssignment
	13, // 10: chainrep.v1.RecoverReplicaCommand.assignment:type_name -> chainrep.v1.ReplicaAssignment
	29, // 11: chainrep.v1.ForwardWriteRequest.operation:type_name -> chainrep.v1.WriteOperation
	3,  // 12: chainrep.v1.CoordinatorService.Bootstrap:input_type -> chainrep.v1.BootstrapRequest
	4,  // 13: chainrep.v1.CoordinatorService.AddNode:input_type -> chainrep.v1.MembershipMutationRequest
	4,  // 14: chainrep.v1.CoordinatorService.BeginDrainNode:input_type -> chainrep.v1.MembershipMutationRequest
	4,  // 15: chainrep.v1.CoordinatorService.MarkNodeDead:input_type -> chainrep.v1.MembershipMutationRequest
	6,  // 16: chainrep.v1.CoordinatorService.RoutingSnapshot:input_type -> chainrep.v1.RoutingSnapshotRequest
	9,  // 17: chainrep.v1.CoordinatorService.ReportReplicaReady:input_type -> chainrep.v1.ReplicaReadyReport
	10, // 18: chainrep.v1.CoordinatorService.ReportReplicaRemoved:input_type -> chainrep.v1.ReplicaRemovedReport
	11, // 19: chainrep.v1.CoordinatorService.ReportNodeHeartbeat:input_type -> chainrep.v1.NodeStatus
	15, // 20: chainrep.v1.CoordinatorService.ReportNodeRecovered:input_type -> chainrep.v1.NodeRecoveryReport
	0,  // 21: chainrep.v1.CoordinatorService.EvaluateLiveness:input_type -> chainrep.v1.Empty
	24, // 22: chainrep.v1.StorageService.Get:input_type -> chainrep.v1.ClientGetRequest
	25, // 23: chainrep.v1.StorageService.Put:input_type -> chainrep.v1.ClientPutRequest
	26, // 24: chainrep.v1.StorageService.Delete:input_type -> chainrep.v1.ClientDeleteRequest
	16, // 25: chainrep.v1.StorageService.AddReplicaAsTail:input_type -> chainrep.v1.AddReplicaAsTailCommand
	17, // 26: chainrep.v1.StorageService.ActivateReplica:input_type -> chainrep.v1.ActivateReplicaCommand
	18, // 27: chainrep.v1.StorageService.MarkReplicaLeaving:input_type -> chainrep.v1.MarkReplicaLeavingCommand
	19, // 28: chainrep.v1.StorageService.RemoveReplica:input_type -> chainrep.v1.RemoveReplicaCommand
	20, // 29: chainrep.v1.StorageService.UpdateChainPeers:input_type -> chainrep.v1.UpdateChainPeersCommand
	21, // 30: chainrep.v1.StorageService.ResumeRecoveredReplica:input_type -> chainrep.v1.ResumeRecoveredReplicaCommand
	22, // 31: chainrep.v1.StorageService.RecoverReplica:input_type -> chainrep.v1.RecoverReplicaCommand
	23, // 32: chainrep.v1.StorageService.DropRecoveredReplica:input_type -> chainrep.v1.DropRecoveredReplicaCommand
	30, // 33: chainrep.v1.StorageService.ForwardWrite:input_type -> chainrep.v1.ForwardWriteRequest
	31, // 34: chainrep.v1.StorageService.CommitWrite:input_type -> chainrep.v1.CommitWriteRequest
	32, // 35: chainrep.v1.StorageService.FetchSnapshot:input_type -> chainrep.v1.FetchSnapshotRequest
	34, // 36: chainrep.v1.StorageService.FetchCommittedSequence:input_type -> chainrep.v1.FetchCommittedSequenceRequest
	5,  // 37: chainrep.v1.CoordinatorService.Bootstrap:output_type -> chainrep.v1.ServerState
	5,  // 38: chainrep.v1.CoordinatorService.AddNode:output_type -> chainrep.v1.ServerState
	5,  // 39: chainrep.v1.CoordinatorService.BeginDrainNode:output_type -> chainrep.v1.ServerState
	5,  // 40: chainrep.v1.CoordinatorService.MarkNodeDead:output_type -> chainrep.v1.ServerState
	8,  // 41: chainrep.v1.CoordinatorService.RoutingSnapshot:output_type -> chainrep.v1.RoutingSnapshotResponse
	5,  // 42: chainrep.v1.CoordinatorService.ReportReplicaReady:output_type -> chainrep.v1.ServerState
	5,  // 43: chainrep.v1.CoordinatorService.ReportReplicaRemoved:output_type -> chainrep.v1.ServerState
	0,  // 44: chainrep.v1.CoordinatorService.ReportNodeHeartbeat:output_type -> chainrep.v1.Empty
	0,  // 45: chainrep.v1.CoordinatorService.ReportNodeRecovered:output_type -> chainrep.v1.Empty
	5,  // 46: chainrep.v1.CoordinatorService.EvaluateLiveness:output_type -> chainrep.v1.ServerState
	28, // 47: chainrep.v1.StorageService.Get:output_type -> chainrep.v1.ReadResult
	27, // 48: chainrep.v1.StorageService.Put:output_type -> chainrep.v1.CommitResult
	27, // 49: chainrep.v1.StorageService.Delete:output_type -> chainrep.v1.CommitResult
	0,  // 50: chainrep.v1.StorageService.AddReplicaAsTail:output_type -> chainrep.v1.Empty
	0,  // 51: chainrep.v1.StorageService.ActivateReplica:output_type -> chainrep.v1.Empty
	0,  // 52: chainrep.v1.StorageService.MarkReplicaLeaving:output_type -> chainrep.v1.Empty
	0,  // 53: chainrep.v1.StorageService.RemoveReplica:output_type -> chainrep.v1.Empty
	0,  // 54: chainrep.v1.StorageService.UpdateChainPeers:output_type -> chainrep.v1.Empty
	0,  // 55: chainrep.v1.StorageService.ResumeRecoveredReplica:output_type -> chainrep.v1.Empty
	0,  // 56: chainrep.v1.StorageService.RecoverReplica:output_type -> chainrep.v1.Empty
	0,  // 57: chainrep.v1.StorageService.DropRecoveredReplica:output_type -> chainrep.v1.Empty
	0,  // 58: chainrep.v1.StorageService.ForwardWrite:output_type -> chainrep.v1.Empty
	0,  // 59: chainrep.v1.StorageService.CommitWrite:output_type -> chainrep.v1.Empty
	33, // 60: chainrep.v1.StorageService.FetchSnapshot:output_type -> chainrep.v1.SnapshotEntry
	35, // 61: chainrep.v1.StorageService.FetchCommittedSequence:output_type -> chainrep.v1.FetchCommittedSequenceResponse
	37, // [37:62] is the sub-list for method output_type
	12, // [12:37] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_chainrep_v1_transport_proto_init() }
func file_chainrep_v1_transport_proto_init() {
	if File_chainrep_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chainrep_v1_transport_proto_rawDesc), len(file_chainrep_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_chainrep_v1_transport_proto_goTypes,
		DependencyIndexes: file_chainrep_v1_transport_proto_depIdxs,
		MessageInfos:      file_chainrep_v1_transport_proto_msgTypes,
	}.Build()
	File_chainrep_v1_transport_proto = out.File
	file_chainrep_v1_transport_proto_goTypes = nil
	file_chainrep_v1_transport_proto_depIdxs = nil
}
